-- UPDATE: 2018-08-08

-- STORES COUNTRIES WHEREIN SUBSCRIPTIONS ARE OFFERED
CREATE TABLE IF NOT EXISTS countries (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  name VARCHAR(256), -- NAME OF THE COUNTRY
	code VARCHAR(2), -- COUNTRY CODE
  CONSTRAINT pk_countries PRIMARY KEY (id)
);